version: "2"

output:
  show-stats: true
  sort-order:
    - file
    - linter

linters:
  default: all

  # Disable specific linters.
  disable:
    - errcheck
    - depguard
    - exhaustruct
    - gochecknoglobals
    - godot
    - gochecknoinits
    - varnamelen
    - revive
    - ireturn
    - wrapcheck
    - tagliatelle

  # All available settings of specific linters.
  settings:
    gocyclo:
      # Minimal code complexity to report.
      # Default: 30 (but we recommend 10-20)
      min-complexity: 15

    misspell:
      # Correct spellings using locale preferences for US or UK.
      # Setting locale to US will correct the British spelling of 'colour' to 'color'.
      # Default is to use a neutral variety of English.
      locale: US

    nestif:
      # Minimal complexity of if statements to report.
      # Default: 5
      min-complexity: 4